export default {
  testUrl: "https://www.bbc.co.uk/food/recipes/sausage_and_gnocchi_bake_80924",
  invalidUrl: "https://www.bbc.co.uk/food/recipes/notarealurl",
  invalidDomainUrl: "www.invalid.com",
  nonRecipeUrl: "https://www.bbc.co.uk/food/recipes/",
  expectedRecipe: {
    name: 'Sausage bake with gnocchi',
    description: 'This easy sausage bake is made with gnocchi rather than pasta. Roasted gnocchi is magical – while the inside stays light and fluffy, the outside goes crisp and golden, like mini roast potatoes.Each serving provides 600 kcal, 24g protein, 47g carbohydrates (of which 10g sugars), 33.5g fat (of which 12g saturates), 8g fibre and 1.8g salt.',
    ingredients: [
      '1 red pepper, deseeded and cut into chunks',
      '1 yellow pepper, deseeded and cut into chunks',
      '1 orange pepper, deseeded and cut into chunks',
      '250g/9oz gnocchi',
      '1 tbsp olive oil',
      '4 pork sausages',
      'salt and freshly ground black pepper'
    ],
    instructions: [
      'Preheat the oven to 200C/180C Fan/Gas 6.',
      'Toss together the peppers, gnocchi, olive oil and a generous amount of salt and pepper on a large baking tray.',
      'Place the sausages on the tray. Roast for 25 minutes, or until the sausages and gnocchi are golden-brown and the peppers are soft and have started to brown around the edges. Serve.'
    ],
    sectionedInstructions: [],
    tags: [
      'quick',
      'our best one-pot meals',
      '10 ingredients or less',
      'absolute bangers',
      '30 minute dinners',
      'all-in-one traybake dinners',
      '5 ingredient meals',
      '6 ingredient one-pot dinners',
      '6 ingredient (or less) traybakes',
      'affordable 30-minute meals for two',
      'cheap sausage',
      'budget dinner',
      'budget traybake dinners',
      'comfort food with a twist',
      'easiest ever recipes for 1-2',
      'easy meal ideas',
      'easy recipes for students',
      'easy sausage suppers',
      'really easy student meals',
      'midweek meal ideas',
      'one dish dinners',
      'quick budget dinners',
      'quick kid-friendly dinners',
      'quick sausage',
      'sausage suppers',
      'summery sausages',
      'super easy',
      'super speedy recipes for 2',
      'the best sausage',
      'time saving recipe hacks',
      'winter warmers',
      'autumn',
      'easy family dinners',
      'picnic',
      'student food',
      'winter',
      'gnocchi',
      'pork sausages',
      'dairy free',
      'nut free',
      'pregnancy friendly',
      'Main course'
    ],
    time: {
      prep: '30 minutes',
      cook: '30 minutes',
      active: '',
      inactive: '',
      ready: '',
      total: ''
    },
    servings: 'Serves 2',
    image: 'https://food-images.files.bbci.co.uk/food/recipes/sausage_and_gnocchi_bake_80924_16x9.jpg'
  }

};
